# Generated by Django 2.2.10 on 2020-11-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassedSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('beginning_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('description', models.TextField()),
                ('questionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passed_surveys', to='questionnaires.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='PassedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('T', 'Text'), ('O', 'OneOf'), ('M', 'Many')], max_length=1)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_questions', to='answers.PassedSurvey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('passed_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='answers.PassedQuestion')),
            ],
        ),
    ]
